providers = ["rust"]

[phases.setup]
nixPkgs = ["nodejs_20", "bun", "pkg-config", "openssl"]
nixLibs = ["gcc-unwrapped"]
aptPkgs = ["libstdc++6", "curl", "wget"]

[phases.install]
cmds = [
    "cd ui && bun install --frozen-lockfile",
    "cd ui && npm install --os=linux --cpu=x64 sharp"
]

[phases.build]
cmds = [
    "cd ui && bun run build",
    "cargo build --release"
]

[start]
cmd = "./target/release/ceokoroji-api"
