providers = ["rust"]

[phases.setup]
nixPkgs = ["bun", "pkg-config", "openssl", "rust-bin.stable.latest.default", "gcc"]
aptPkgs = ["libstdc++6", "curl", "wget"]

[phases.install]
cmds = [
    "curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -",
    "sudo apt-get install -y nodejs",
    "rm -f ui/bun.lock",
    "cd ui && bun install",
    "cd ui && npm install --os=linux --cpu=x64 sharp"
]

[phases.build]
dependsOn = ["install"]
cmds = [
    "cd ui && bun run build",
    "cargo build --release"
]

[start]
cmd = "./target/release/ceokoroji-api"
