name: Migrate database

on:
    pull_request:
    push:
        branches:
            - main
    workflow_dispatch: 

jobs:
    release:
        runs-on: ubuntu-latest

        env:
            SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
            SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_DB_PASSWORD }}
            PROJECT_ID: rbynijptkgcyiukgzimc

        steps:
            - uses : actions/checkout@v3

            - uses: supabase/setup-cli@v1
              with:
                version: latest

            - name: Link to production database
              run: supabase link --project-ref $PROJECT_ID

            - name: Push migrations
              run: supabase db push